//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "todo_lists")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::todo_list_items::Entity")]
    TodoListItems,
}

impl Related<super::todo_list_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TodoListItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
