//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "todo_list_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    pub todo_list_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::todo_lists::Entity",
        from = "Column::TodoListId",
        to = "super::todo_lists::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TodoLists,
}

impl Related<super::todo_lists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TodoLists.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
